name: Pull request labeler
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Teste de execucao
        run: echo Validacao de execucao!
