name: Pull request labeler
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: triage
    steps:
      - name: Teste de execucao
        run: |
          echo Validacao de execucao!
          echo token ${{ secrets.GITHUB_TOKEN }}
