name: Pull request labeler
on:
  push:
    branches: [main]
  pull_requests:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    -name: Teste de execução
    run: echo Validação de execução!
