name: Pull request labeler
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      -name: Teste de execução
      run: echo Validação de execução!
